# Pod user with userns set to "node" mode and special features.
apiVersion: v1
kind: Pod
metadata:
  name: node-special
  namespace: default
  annotations:
    alpha.kinvolk.io/userns: "node"
spec:
  restartPolicy: Never
  containers:
  - name: container1
    image: busybox
    command: ["sh"]
    args: ["-c", "sleep infinity"]
  hostNetwork: true
