# Pod user with userns set to "pod" mode and special features.
# The pod creation will fail.
apiVersion: v1
kind: Pod
metadata:
  name: pod-userns-pod-special
  namespace: default
  annotations:
    alpha.kinvolk.io/userns: "pod"
spec:
  restartPolicy: Never
  containers:
  - name: pod-userns
    image: busybox
    command: ["sh"]
    args: ["-c", "sleep infinity"]
  # TODO: add more special features here.
  hostNetwork: true
