apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: prestop
  name: prestop
  namespace: default
spec:
  selector:
    matchLabels:
      run: prestop
  template:
    metadata:
      annotations:
        # XXX: value should be a json encoded list. That means, each string
        # should be enclosed with double-quote
        #alpha.kinvolk.io/sidecar: '["sidecar-1", "sidecar-2"]'
      labels:
        run: prestop
    spec:
      initContainers:
      - name: init-1
        image: debian
        command: ["/bin/sh", "-c", "/logs/logs.sh Initialization done"]
        env:
          - name: NAME
            value: "init-1"
        volumeMounts:
        - name: logs
          mountPath: /logs
      containers:
      - name: debian-1
        image: debian
        command: ["/logs/logs.sh", "sleep"]
        env:
          - name: NAME
            value: "debian-1"
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "/logs/logs.sh PreStop Will-Sleep; sleep 2; /logs/logs.sh PreStop-After-Sleep; exit 0"]
        volumeMounts:
        - name: logs
          mountPath: /logs
      volumes:
      - name: logs
        hostPath:
          path: /tmp/logs/
