apiVersion: v1
kind: Pod
metadata:
  name: test-shm
  namespace: default
  annotations:
    alpha.kinvolk.io/userns: "pod"
spec:
  restartPolicy: Never
  containers:
  - name: reader
    image: mauriciovasquezbernal/sharedmemoryexample
    command: ["bash"]
    args: ["-c", 'content=$(/reader); if [[ "$content" != "bar" ]]; then exit 1; else exit 0; fi']
  initContainers:
  - name: writer
    image: mauriciovasquezbernal/sharedmemoryexample
    command: ["/writer"]
    args: ["bar"]
